export const COUNT = {
  FIRST_MOBILE_PAGE_COUNT: 4,
  FIRST_TABLET_PAGE_COUNT: 7,
  FIRST_DESKTOP_PAGE_COUNT: 8,
  OTHER_MOBILE_PAGE_COUNT: 5,
  OTHER_TABLET_PAGE_COUNT: 8,
  OTHER_DESKTOP_PAGE_COUNT: 9,
};
export const FIRST_PAGE = 1;
export const QUANTITY = {
  DESKTOP_BUTTONS_QUANTITY: 3,
  MOBILE_BUTTONS_QUANTITY: 6,
};
